from datetime import datetime, timezone

from PyQt6.QtWidgets import (
    QCheckBox,
    QDialog,
    QDialogButtonBox,
    QFormLayout,
    QLabel,
    QLineEdit,
    QMessageBox,
    QPlainTextEdit,
    QVBoxLayout,
)

from ssrf_explorer.config import Authorization


AUTHORIZATION_TEXT = (
    "By proceeding I attest that:\n"
    "  \u2022 I own the target system, OR\n"
    "  \u2022 I hold explicit written authorization to perform security testing against it\n"
    "  \u2022 My testing stays within the declared scope\n"
    "  \u2022 I accept responsibility for all traffic generated by this tool."
)


class AuthGateDialog(QDialog):
    """Mandatory authorization confirmation. No scan runs without it."""

    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        self.setWindowTitle("Authorization Required")
        self.setModal(True)
        self.resize(560, 440)

        layout = QVBoxLayout(self)
        layout.addWidget(QLabel("<b>Authorization gate</b>"))

        body = QPlainTextEdit(AUTHORIZATION_TEXT)
        body.setReadOnly(True)
        body.setFixedHeight(140)
        layout.addWidget(body)

        form = QFormLayout()
        self.operator = QLineEdit()
        self.operator.setPlaceholderText("Your name / handle")
        self.engagement = QLineEdit()
        self.engagement.setPlaceholderText(
            "Engagement ID, bug bounty program, PO number, etc."
        )
        form.addRow("Operator:", self.operator)
        form.addRow("Authorization reference:", self.engagement)
        layout.addLayout(form)

        self.attest = QCheckBox("I attest to all of the above.")
        layout.addWidget(self.attest)

        buttons = QDialogButtonBox(
            QDialogButtonBox.StandardButton.Ok
            | QDialogButtonBox.StandardButton.Cancel
        )
        buttons.accepted.connect(self._accept)
        buttons.rejected.connect(self.reject)
        layout.addWidget(buttons)

        self.result_auth: Authorization | None = None

    def _accept(self) -> None:
        if not self.attest.isChecked():
            QMessageBox.warning(
                self,
                "Attestation required",
                "You must tick the attestation checkbox to proceed.",
            )
            return
        if not self.operator.text().strip() or not self.engagement.text().strip():
            QMessageBox.warning(
                self,
                "Missing fields",
                "Operator and authorization reference are required.",
            )
            return
        self.result_auth = Authorization(
            attested=True,
            operator=self.operator.text().strip(),
            engagement_ref=self.engagement.text().strip(),
            timestamp=datetime.now(timezone.utc).isoformat(),
        )
        self.accept()
