import React, { useEffect, useState } from 'react';
import { api } from '../api.js';

export default function AuthGate({ target, onAttested }) {
  const [operator, setOperator] = useState('');
  const [engagementRef, setRef] = useState('');
  const [attested, setAttested] = useState(false);
  const [existing, setExisting] = useState(null);
  const [err, setErr] = useState('');
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    (async () => {
      try {
        const a = await api.getAuthorization(target._id);
        if (a) setExisting(a);
      } catch {}
    })();
  }, [target._id]);

  const submit = async (e) => {
    e.preventDefault();
    setErr(''); setBusy(true);
    try {
      if (!attested || !operator || !engagementRef) {
        throw new Error('All fields + attestation required.');
      }
      const rec = await api.authorize(target._id, { operator, engagementRef, attested: true });
      setExisting(rec);
      onAttested(rec);
    } catch (e) { setErr(e.message); }
    finally { setBusy(false); }
  };

  if (existing) {
    return (
      <div className="card">
        <h2>2 · Authorization <span className="tag" style={{ background: '#1c4525', color: '#b9f0c5' }}>attested</span></h2>
        <p className="muted">
          Operator: <span className="code">{existing.operator}</span><br />
          Reference: <span className="code">{existing.engagementRef}</span><br />
          Attested at: <span className="code">{existing.attestedAt}</span>
        </p>
        <button className="secondary" onClick={() => setExisting(null)}>Re-attest</button>
      </div>
    );
  }

  return (
    <form className="card" onSubmit={submit}>
      <h2>2 · Authorization attestation</h2>
      <div className="banner">
        By proceeding I attest that I own this system OR hold explicit written authorization to perform
        security testing against it. All traffic generated by this tool is my responsibility.
      </div>
      <label>Operator (your name / handle)</label>
      <input value={operator} onChange={(e) => setOperator(e.target.value)} />
      <label>Authorization reference</label>
      <input value={engagementRef} onChange={(e) => setRef(e.target.value)}
        placeholder="Engagement ID, bug bounty program, PO number..." />
      <label style={{ marginTop: 12 }}>
        <input type="checkbox" checked={attested} onChange={(e) => setAttested(e.target.checked)}
          style={{ width: 'auto', marginRight: 6 }} />
        I attest to all of the above.
      </label>
      {err && <div className="banner err" style={{ marginTop: 12 }}>{err}</div>}
      <div style={{ marginTop: 12 }}>
        <button className="primary" type="submit" disabled={busy}>Attest and unlock scan</button>
      </div>
    </form>
  );
}
